use_frameworks!

target 'SwipeableView_Example' do
  pod 'SwipeableView', :path => '../'

  target 'SwipeableView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
